[package]
name = "bark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = { version = "2.4.0", features = ["bytemuck"] }
bytemuck = { version = "1.13.1", features = ["derive", "extern_crate_alloc"] }
cpal = "0.15.2"
derive_more = "0.99.17"
libc = "0.2.147"
nix = { version = "0.26.2", features = ["time", "socket", "net", "poll", "user", "hostname"], default-features = false }
opus = "0.3.0"
rand = "0.8.5"
ringbuf = "0.3.3"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.105"
socket2 = "0.5.3"
static_assertions = "1.1.0"
structopt = "0.3.26"
termcolor = "1.2.0"
toml = "0.7.6"
xdg = "2.5.2"
